export const messageEN = {
 	address				: "Address",
 	language			: "Language",
 	admin				: "Admin",
 	currency_type		: "Currency type", 
 	search				: "Search",
 	filter				: "Filter",
 	price				: "Price",
 	star				: "Stars",
 	any					: "Any",
 	rating				: "Rating",
 	store_location		: "Store Location",
 	center_city			: "Center City",
 	other				: "Other",
 	choose				: "Choose",
 	view_price			: "View Price",
 	view_image			: "View Image",
 	image				: "Image",
 	info				: "Infomation",
 	comment				: "Comment",
 	share_this			: "Share This Shop",
 	list_employ			: "List Employee",
 	booking				: "Booking"
};
